name: search_function
description: You can search with binary,linear and jump search. It is very comfortable to use.
version: 1.1.2
homepage: https://github.com/Abrorov-javohir/search_function
repository: https://github.com/Abrorov-javohir/search_function

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
